# Generated by Django 5.1.3 on 2024-11-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=32, verbose_name='марка автомобиля')),
                ('model', models.CharField(max_length=32, verbose_name='модель автомобиля')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год выпуска')),
                ('description', models.CharField(max_length=1024, verbose_name='описание автомобиля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата и время последнего обновления записи')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'автомобили',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='содержание комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания комментария')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
