# Generated by Django 5.1.3 on 2024-11-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarBlog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='описание автомобиля'),
        ),
    ]
